{ pkgs, lib, config, xlib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."openhands-app-" = {
    image = "localhost/openhands:latest";
    environment = {
      "AGENT_SERVER_IMAGE_REPOSITORY" = "ghcr.io/openhands/agent-server";
      "AGENT_SERVER_IMAGE_TAG" = "31536c8-python";
      "WORKSPACE_MOUNT_PATH" = "/mnt/c/Users/oqyude/Desktop/openhands/workspace";
    };
    volumes = [
      "/home/oqyude/.openhands:/.openhands:rw"
      "/mnt/c/Users/oqyude/Desktop/openhands/workspace:/opt/workspace_base:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=openhands"
      "--network=openhands_default"
    ];
  };
  systemd.services."podman-openhands-app-" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-openhands_default.service"
    ];
    requires = [
      "podman-network-openhands_default.service"
    ];
    partOf = [
      "podman-compose-openhands-root.target"
    ];
    wantedBy = [
      "podman-compose-openhands-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-openhands_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f openhands_default";
    };
    script = ''
      podman network inspect openhands_default || podman network create openhands_default
    '';
    partOf = [ "podman-compose-openhands-root.target" ];
    wantedBy = [ "podman-compose-openhands-root.target" ];
  };

  # Builds
  systemd.services."podman-build-openhands-app-" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /mnt/c/Users/oqyude/Desktop/openhands
      podman build -t openhands:latest -f ./containers/app/Dockerfile .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-openhands-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
