# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      availableKernelModules = [
        "ahci"
        "xhci_pci"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "sdhci_pci"
      ];
      kernelModules = [ ];
    };
    kernel = {
      sysctl = {
        "fs.inotify.max_user_watches" = "204800";
      };
    };

    kernelModules = [
      "kvm-intel"
      "coretemp"
    ];
    kernelPackages = pkgs.linuxPackages_latest;
    hardwareScan = true;
    blacklistedKernelModules = [
      ""
    ];
    extraModulePackages = [ ];
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  hardware = {
    bluetooth.enable = false;
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-partlabel/disk-main-root";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/disk-main-ESP";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/server" = {
    device = "/dev/disk/by-partlabel/Server";
    fsType = "ext4";
    options = [
      "nofail"
      "x-systemd.device-timeout=0"
    ];
  };

  #swapDevices =
  #  [ { device = "/dev/disk/by-partlabel/disk-main-swap"; }
  #  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
